development:
  adapter: postgresql
  encoding: utf8
  database: udemy
  username: user
  password: admin

test:
  adapter: postgresql
  encoding: utf8
  database: udemy
  username: user
  password: admin

